// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBz_tOHx3UBM9CfvYpddTp-Mi_5zesUnO0',
    appId: '1:83956234658:web:fb4c45c82d563ae51adafb',
    messagingSenderId: '83956234658',
    projectId: 'milkshop-5d8a1',
    authDomain: 'milkshop-5d8a1.firebaseapp.com',
    storageBucket: 'milkshop-5d8a1.appspot.com',
    measurementId: 'G-3Y5JW421B1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBr8LDjZfm26G9L_94ZbznC4KbOXyYP6RY',
    appId: '1:83956234658:android:2c5505318436e6bf1adafb',
    messagingSenderId: '83956234658',
    projectId: 'milkshop-5d8a1',
    storageBucket: 'milkshop-5d8a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA27osDmFOJ-HHkV5ZGjt_REr4pAhMC8xU',
    appId: '1:83956234658:ios:54e2433025cf5c491adafb',
    messagingSenderId: '83956234658',
    projectId: 'milkshop-5d8a1',
    storageBucket: 'milkshop-5d8a1.appspot.com',
    iosClientId: '83956234658-hffiof30m7hka4rc25cacphvqfd5jli2.apps.googleusercontent.com',
    iosBundleId: 'com.example.milkshop',
  );
}
